### ISSUE TITLE
关于工程部署和编译的问题

### ISSUE THREAD

**Issue by W-Webber** [copyliu/bililive_dm#183]
操作系统：Windows 10
IDE：Rider
.NET SDK：8.0.100、8.0.300
编译出现问题：

![Image](https://github.com/user-attachments/assets/85cbe5d8-ddd4-4365-a8b8-f7cc1da20df9)

有几个疑问：
1. 截图中报错该如何解决？
2. 是否存在或可以提供一份本地部署工程的环境配置文档？
3. 是否会发布新版本安装包？
4. 是否会发布最新的`BilibiliDM_PluginFramework.dll`？（`https://soft.ceve-market.org/bilibili_dm/sdk.7z`提供的dll好像是旧版本，我看到`MsgTypeEnum`等枚举和仓库中最新的代码不一致）

**Comment by copyliu** [comment]
首先你需要一个已经安装了VC++的VS, 虽然确实能用rider编译但不建议.
然后你需要确保执行了 `git submodule update --init --recursive` 以获取子模块

经查确实发布版SDK忘了更新, 但应该不影响使用.

**Comment by copyliu** [comment]
现在项目中的 appveyor CI的配置如下

```yaml
version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    git submodule update --init --recursive

    mkdir %APPVEYOR_BUILD_FOLDER%\Bililive_dm\Win32

    mkdir %APPVEYOR_BUILD_FOLDER%\Bililive_dm\x64

    nuget restore Bililive_dm.sln
build:
  project: Bililive_dm.sln
  parallel: true
  verbosity: minimal
```
